### ISSUE TITLE
USER STORY: Login/Logout

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#11]
As a **Site User** I can **easily login and logout of my account using my credentials** so that I can **access my personal account information.**

**Acceptance Criteria**
- Users can choose to login and logout whenever they please
- When users are logged in they can access their user profile

**Tasks**
- [x] Task 1: Configure allauth templates
- [x] Task 2: Display login/logout links
- [x] Task 3: Ensure logged in users can access relevant information
