### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#14]
As a **Site User** I can **have my own personalised user profile** so that I can **view my order history, confirmations, and save my 
personal payment/delivery information.**

**Acceptance Criteria**
- User can access a personal user profile that contains all of their data.
- Users can edit and save their own information

**Tasks**
- [x] Task 1: Create model for user profile
- [x] Task 2: Create view code and wire url
- [x] Task 3: Create and style template
