### ISSUE TITLE
USER STORY: Filters

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#15]
As a **Shopper** I can **use filters to sort the list of available products by category, price range and popularity** so that I can **easily find products that match my preferences and budget.**

**Acceptance Criteria**
- User can choose from a selection of filters that sort products in a defined way
- Producs of highest relevance will be shown first

**Tasks**
- [x] Task 1: Add sort select box to template
- [x] Task 2: Configure select box with different filters
- [x] Task 3: Add JavaScript to filter products
