### ISSUE TITLE
USER STORY: Product Categories

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#16]
As a **Shopper** I can **sort an individual category of product** so that I can **locate the best-priced or best-rated product in a certain category, sort the products in that category by name.**

**Acceptance Criteria**
- Users can select different categories through the naviagtion menu.
- Each category will show different products depending on the chosen category.

**Tasks**
- [x] Task 1: Add categories model
- [x] Task 2: Create categories
- [x] Task 3: Add catories to nav menu
- [x] Task 4: Display products that match selected category
