### ISSUE TITLE
USER STORY: Product List

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#2]
As a **Shopper** I can **view a list of products** so that I can **select some to purchase.**

**Acceptance Criteria**
- List of products and information clearly shown

**Tasks**
- [x] Task 1: Add view code for products page
- [x] Task 2: Add content to template
- [x] Task 3: Wire up url
