### ISSUE TITLE
USER STORY: Add to Cart

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#20]
As a **Shopper** I can **easily add items to my shopping cart** so that I can **checkout an buy my chosen products.**

**Acceptance Criteria**
- Users can select to add various products into their cart
- A confirmation notification will be shown when an item has been added successfully

**Tasks**
- [x] Task 1: Create view code for adding products to the cart
- [x] Task 2: Configure template to show cart
- [x] Task 3: Incorportate success message
