### ISSUE TITLE
USER STORY: Buy Now Button

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#21]
As a **Shopper** I can **easily buy a single prouduct by clicking buy now** so that I can **quickly chekout if I am buying a specific product only.**

**Acceptance Criteria**
- User can click one button to automatically add an item to their cart and go to the checkout

**Tasks**
- [ ] Task 1: Write view code for adding to cart/checkout
- [ ] Task 2: Add 'Buy Now' button to template
- [ ] Task 3: Style button
