### ISSUE TITLE
USER STORY: Secure and Easy Payment System

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#24]
As a **Shopper** I can **have a secure and straightforward checkout process** so that I can **complete my purchase efficiently and with confidence that my information is safe.**

**Acceptance Criteria**
- User is prompted to enter relevant and necessary information only.
- Payment process is easy to follow and understand.
- Payments complete with no errors.

**Tasks**
- [x] Task 1: Set up models for delivery/shipping information
- [x] Task 2: Create forms for user info
- [x] Task 3: Add forms to template/view
- [x] Task 4: Install and configure Stripe payments
