### ISSUE TITLE
USER STORY: Order Confirmation

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#25]
As a **Shopper** I can **view the confirmation of my order after checkout** so that I can **verify that the information entered is correct.**

**Acceptance Criteria**
- User is presented with a breakdown of what they have purchased and the information that they entered.
- User can contact the company if any information they entered was incorrect.

**Tasks**
- [x] Task 1: Set up model to save delivery/order info
- [x] Task 2: Create view/add url
- [x] Task 3: Create template to display delivery/order information to user
