### ISSUE TITLE
USER STORY: Newsletter

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#27]
As a **Site User** I can **sign up to a news letter** so that I can **get information on upcoming products, deals and offers.**

**Acceptance Criteria**
- Users can enter their email to sign up for regular emails on products, deals, promotional offers etc.
- Notification shows confirming that the user has successfully signed up to the newsletter.

**Tasks**
- [x] Task 1: Create model for user information
- [x] Task 2: Create view/url
- [x] Task 3: Add form input to footer
