### ISSUE TITLE
USER STORY: Contact Form

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#28]
As a **Site User** I can **fill in a contact form** so that I can **gain direct contact with the company for any queries on items such as more information, order inquiries or product availibility.**

**Acceptance Criteria**
- Users can enter information into a form that will be sent directly to the company.
- Questions can be asked regarding orders, delivery information as well as othe product information.

**Tasks**
- [x] Task 1: Add model for saving form information
- [x] Task 2: Create form for inputting info
- [x] Task 3: Create view/url
- [x] Task 4: Set up template
