### ISSUE TITLE
USER STORY: Dedicated Forum

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#29]
As a **Site User** I can **go to a dedicated forum** so that I can **ask questions to staff members and site users about tech products and other computer related items.**

**Acceptance Criteria**
- Users can go to a separate page that allows them to browse through questions and answers about all types of computer related inquiries

**Tasks**
- [ ] Task 1: Create models
- [ ] Task 2: Create views
- [ ] Task 3: Wire up urls
- [ ] Task 4: Create templates
