### ISSUE TITLE
USER STORY: Stock Availability

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#3]
As a **Shopper** I can **view if a product is in stock** so that I can **avoid dissapointment of long shipping times due to availability**

**Acceptance Criteria**
- Label shown clearly identifies if a product is in stock or not

**Tasks**
- [x] Task 1: Add stock boolean field to model
- [ ] Task 2: Write view code to handle if item is in stock
- [x] Task 3: Use template to display in/out of stock label
