### ISSUE TITLE
USER STORY: Create Forum Post

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#30]
As a **Site User** I can **post my inquiries and issues to a central location** so that I can **get feedback from other users that have had similar issues or are more informed than I am.**

**Acceptance Criteria**
- Logged in users can create posts and ask questions on the forums page

**Tasks**
- [ ] Task 1: Create post form
- [ ] Task 2: Configure view and url
- [ ] Task 3: Set up template
