### ISSUE TITLE
USER STORY: Comment/Reply on Forum Posts

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#33]
As a **Site User** I can **comment/reply to other users posts** so that I can **help them with an issue or give them my 
opinion/feedback.**

**Acceptance Criteria**
- Logged in users can reply to a forum post to give their input

**Tasks**
- [ ] Task 1: Create reply model
- [ ] Task 2: Create reply view
- [ ] Task 3: Add reply section to post detail view
