### ISSUE TITLE
USER STORY: Post Detail View

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#34]
As a **Site User** I can **open a detailed view of each post** so that I can **read the full post.**

**Acceptance Criteria**
- Each post can be opened on its own page to view more information about it

**Tasks**
- [ ] Task 1: Make posts clickable
- [ ] Task 2: Redirect each post to their own detailed forum post page
- [ ] Task 3: Structure and style detailed page
