### ISSUE TITLE
USER STORY: Forum Post Upvotes

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#36]
As a **Site User** I can **upvote forum posts** so that I can **let other users know if the post was helpful.**

**Acceptance Criteria**
- Logged in users can click a upvote button to add an upvote to the post to show it was helpful

**Tasks**
- [ ] Task 1: Create upvote button
- [ ] Task 2: Add view for upvoting or un-upvoting a post
- [ ] Task 3: Change style of button based on if the post has been upvoted or not
