### ISSUE TITLE
USER STORY: Adding Products

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#38]
As a **Site Admin** I can **add products** so that I can **add new products to the store**

**Acceptance Criteria**
- Site admins can add new products to the store that will be displayed on the products pages

**Tasks**
- [ ] Task 1: Create form for adding product
- [ ] Task 2: Configure view/url
- [ ] Task 3: Create template
