### ISSUE TITLE
USER STORY: Wishlist

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#45]
As a **Site User** I can **add items to a wishlist** so that I **don't have to go looking for a specific item again on the site**

**Acceptance Criteria**
- Wishlist button appears on each product
- Users can add and remove items from their wishlist
- The wishlist can be seen on its own page

**Tasks**
- [x] Task 1: Create new app
- [x] Task 2: Create models
- [x] Task 3: Create views and urls
- [x] Task 4: Create template
