### ISSUE TITLE
USER STORY: Product Details

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#5]
As a **Shopper** I can **view product details, including images, descriptions, and prices** so that I can **get a comprehensive understanding of the product before making a decision.**

**Acceptance Criteria**
- Users can click on each product to bring them to a new page
- Each detailed product view will show information such as decriptions, prices, ratings etc.

**Tasks**
- [x] Task 1: Make products clickable
- [x] Task 2: Redirect each product to its own individual page
- [x] Task 3: Structure and style each detail page
