### ISSUE TITLE
USER STORY: Multiple Product Images

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#6]
As a **Shopper** I can **scroll through the images of a product** so that I can **see more of the product to make an informed purchase**

**Acceptance Criteria**
- Users can scroll through multiple images of a single product 

**Tasks**
- [ ] Task 1: Add image field to model
- [ ] Task 2: Create template for displaying multiple images
- [ ] Task 3: Style images
