### ISSUE TITLE
USER STORY: Deals and Special Offers

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#7]
As a **Shopper** I can **quickly identify deals, clearance items and special offers** so that I can **take advantage of special savings on products I'd like to purchase.**

**Acceptance Criteria**
- Users can easily navigate to specified sections with deals and special offers clearly outlined

**Tasks**
- [x] Task 1: Create specified categories
- [x] Task 2: Assign products to categories
- [x] Task 3: Allow users to filter to chosen categories
