### ISSUE TITLE
USER STORY: Total Price

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#8]
As a **Shopper** I can **easily view the total price of my purchases at any time** so that **I can avoid overspending.**

**Acceptance Criteria**
- The total accumulated price of a users order will be displayed at all times on the site
- The total price will also be shown in the cart and checkout areas

**Tasks**
- [x] Task 1: Set price / delivery variables
- [x] Task 2: Write code to dynamically calculate total cost
- [x] Task 3: Display price on templates
