### ISSUE TITLE
USER STORY: Create Account

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/NexTech#9]
As a **Site User** I can **easily create a new account using my email and password** so that **I have a personal account and will be able to view my profile.**

**Acceptance Criteria**
- Users can sign up to the site with the relevant information

**Tasks**
- [x] Task 1: Install allauth
- [x] Task 2: Update requirements, urls, & settings
- [x] Task 3: Edit/style templates
